version: "3"

services:

  account-database:
    image: nelsonabmdocker/account-database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  compute-interest-api:
    image: nelsonabmdocker/compute-interest-api
    ports:
      - "8080:8080" 
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - "account-database"

  account-summary:
    image: nelsonabmdocker/account-summary
    ports:
      - "5001:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  transaction-generator:
    image: nelsonabmdocker/transaction-generator
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
