version: "3"

services:

  account-api:
    build: 
      context: ./compute-interest-api
    environment:
      DATABASE_URL: http//account-database
      
  account-database:
    image: jzaccone/account-database
